// Generated by CoffeeScript 1.10.0
var cheerio, extend, truncate;

cheerio = require('cheerio');

extend = function(obj, dft) {
  var k, v;
  if (obj == null) {
    obj = {};
  }
  for (k in dft) {
    v = dft[k];
    if (obj[k] != null) {
      continue;
    }
    obj[k] = v;
  }
  return obj;
};


/**
 * truncate html
 * truncate(html, [length], [options])
 * @param  {String}        html    html string to truncate
 * @param  {Object|number} length
 * @param  {Object|null}   options
 *                         {
 *                           stripTags: false, // remove all tags, default false
 *                           ellipsis: '...', // ellipsis sign, default '...'
 *                           decodeEntities: false, // decode html entities before counting length, default false
 *                           excludes: '', // elements' selector you want ignore, default none
 *                           length: 10, // how many letters you want reserve, default none
 *                           keepWhitespaces: false // keep whitespaces, by default continuous spaces will be replaced with one space, default false
 *                         }
 * @return {String}
 * @example
 * truncate('<p>wweeweewewwe</p>', 10)
 * truncate('<p>wweeweewewwe</p>', 10, {stripTags: true})
 * truncate('<p>wweeweewewwe</p>', {stripTags: true, length: 10})
 */

truncate = function(html, length, options) {
  var $, $html, keepWhitespaces, text, travelChildren;
  switch (typeof length) {
    case 'object':
      options = length;
      break;
    case 'number':
      if (typeof options === 'object') {
        options.length = length;
      } else {
        options = {
          length: length
        };
      }
  }
  options = extend(options, truncate.defaultOptions);
  if (!html || isNaN(options.length) || options.length <= 0) {
    return html;
  }
  if (typeof html === 'object') {
    html = $(html).html();
  }
  $ = cheerio.load("<div>" + html + "</div>", {
    decodeEntities: options.decodeEntities
  });
  $html = $('div').first();
  if (options.excludes) {
    if (!Array.isArray(options.excludes)) {
      options.excludes = [options.excludes];
    }
    $html.find(options.excludes.join(',')).remove();
  }
  if (options.stripTags) {
    text = $html.text().replace(/\s+/, ' ');
    if (text.length <= options.length) {
      return text;
    } else {
      return text.substr(0, options.length) + options.ellipsis;
    }
  }
  length = options.length;
  keepWhitespaces = options.keepWhitespaces;
  travelChildren = function($ele) {
    return $ele.contents().each(function() {
      var subLength, textLength;
      switch (this.type) {
        case 'text':
          if (length <= 0) {
            if (length === 0) {
              this.data = options.ellipsis;
              --length;
            } else {
              $(this).remove();
            }
            return;
          }
          text = $(this).text();
          if (keepWhitespaces) {
            textLength = 0;
            subLength = 0;
            text.replace(/(\S*)(\s*)/g, function($0, $1, $2) {
              var $2Len;
              if (textLength > length) {
                return;
              }
              if ($1.length >= length) {
                subLength += length;
                textLength += $1.length;
                length = 0;
                return;
              }
              textLength += $1.length;
              subLength += $1.length;
              length -= $1.length;
              $2Len = !!$2.length;
              if ($2Len >= length) {
                subLength += $2Len;
                textLength += $2.length;
                length = 0;
                return;
              }
              textLength += $2Len;
              subLength += $2.length;
              length -= $2Len;
            });
          } else {
            text = text.replace(/\s+/g, ' ');
            textLength = text.length;
            subLength = Math.min(textLength, length);
          }
          if (textLength <= length) {
            this.data = text;
            return length -= textLength;
          } else {
            this.data = text.substr(0, subLength) + options.ellipsis;
            return length = -1;
          }
          break;
        case 'tag':
          if (length <= 0) {
            if (length === 0) {
              this.type = 'text';
              this.data = options.ellipsis;
              return --length;
            } else {
              return $(this).remove();
            }
          } else {
            return travelChildren($(this));
          }
          break;
        default:
          return $(this).remove();
      }
    });
  };
  travelChildren($html);
  return $html.html();
};

truncate.defaultOptions = {
  stripTags: false,
  ellipsis: '...',
  decodeEntities: false
};

module.exports = truncate;
